import type { Product } from '@/types';

export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Lagos Nights Silk Shirt',
    slug: 'lagos-nights-silk-shirt',
    description: 'Premium silk shirt featuring a relaxed silhouette, tonal script embroidery, and custom horn buttons. Designed for balmy evenings and rooftop gatherings across Lagos.',
    price: 4500000,
    compareAtPrice: 5500000,
    category: 'Tops',
    materials: '100% Habotai Silk',
    careInstructions: 'Dry clean only. Steam with low heat.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-1-1', url: '/images/antho-shoot/IMG_3806.JPG', alt: 'Lagos Nights Silk Shirt Front', position: 0 },
      { id: 'img-1-2', url: '/images/antho-shoot/Snapchat-1522984318.jpg', alt: 'Lagos Nights Silk Shirt Detail', position: 1 },
      { id: 'img-1-3', url: '/images/antho-shoot/IMG_3807.JPG', alt: 'Lagos Nights Silk Shirt Lifestyle', position: 2 },
    ],
    variants: [
      { id: 'v-1-s', size: 'S', color: 'Midnight Black', colorHex: '#0A0A0A', stock: 10 },
      { id: 'v-1-m', size: 'M', color: 'Midnight Black', colorHex: '#0A0A0A', stock: 15 },
      { id: 'v-1-l', size: 'L', color: 'Midnight Black', colorHex: '#0A0A0A', stock: 12 },
    ],
  },
  {
    id: 'prod-2',
    name: 'Harmattan Heavyweight Hoodie',
    slug: 'harmattan-heavyweight-hoodie',
    description: 'Ultra-heavyweight 500gsm cotton fleece hoodie with dropped shoulders, slightly cropped body, and a structured double-lined hood.',
    price: 6500000,
    compareAtPrice: null,
    category: 'Tops',
    materials: '100% Organic French Terry Cotton (500gsm)',
    careInstructions: 'Machine wash cold inside out. Hang to dry.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-2-1', url: '/images/antho-shoot/IMG_3807.JPG', alt: 'Harmattan Heavyweight Hoodie Front', position: 0 },
      { id: 'img-2-2', url: '/images/antho-shoot/Snapchat-1782284509.jpg', alt: 'Harmattan Heavyweight Hoodie Side', position: 1 },
    ],
    variants: [
      { id: 'v-2-m', size: 'M', color: 'Washed Stone', colorHex: '#78716C', stock: 8 },
      { id: 'v-2-l', size: 'L', color: 'Washed Stone', colorHex: '#78716C', stock: 14 },
      { id: 'v-2-xl', size: 'XL', color: 'Washed Stone', colorHex: '#78716C', stock: 5 },
    ],
  },
  {
    id: 'prod-3',
    name: 'Victoria Island Tailored Trousers',
    slug: 'vi-tailored-trousers',
    description: 'Wide-leg tailored trousers made from a premium wool-blend. Features double front pleats, hidden side adjusters, and a clean drape.',
    price: 5500000,
    compareAtPrice: 6500000,
    category: 'Bottoms',
    materials: '80% Tropical Wool, 20% Silk',
    careInstructions: 'Dry clean only.',
    isPublished: true,
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-3-1', url: '/images/antho-shoot/IMG_3801.JPG', alt: 'VI Tailored Trousers Front', position: 0 },
      { id: 'img-3-2', url: '/images/antho-shoot/Snapchat-396574672.jpg', alt: 'VI Tailored Trousers Fit', position: 1 },
    ],
    variants: [
      { id: 'v-3-30', size: '30', color: 'Charcoal', colorHex: '#1C1917', stock: 5 },
      { id: 'v-3-32', size: '32', color: 'Charcoal', colorHex: '#1C1917', stock: 10 },
      { id: 'v-3-34', size: '34', color: 'Charcoal', colorHex: '#1C1917', stock: 8 },
    ],
  },
  {
    id: 'prod-4',
    name: 'Eko Essential Boxy Tee',
    slug: 'eko-essential-tee',
    description: 'The definitive luxury heavyweight t-shirt. 280gsm combed cotton, tight rib collar, and relaxed drop-shoulder cut.',
    price: 2500000,
    compareAtPrice: null,
    category: 'Tops',
    materials: '100% Combed Cotton (280gsm)',
    careInstructions: 'Machine wash cold with like colors.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-4-1', url: '/images/antho-shoot/IMG_3803.JPG', alt: 'Eko Essential Tee Front', position: 0 },
      { id: 'img-4-2', url: '/images/antho-shoot/Snapchat-617620438.jpg', alt: 'Eko Essential Tee Back', position: 1 },
    ],
    variants: [
      { id: 'v-4-s', size: 'S', color: 'Off-White', colorHex: '#F5F5F4', stock: 20 },
      { id: 'v-4-m', size: 'M', color: 'Off-White', colorHex: '#F5F5F4', stock: 30 },
      { id: 'v-4-l', size: 'L', color: 'Off-White', colorHex: '#F5F5F4', stock: 25 },
    ],
  },
  {
    id: 'prod-5',
    name: 'Adire Modern Camp Shirt',
    slug: 'adire-camp-collar',
    description: 'Contemporary camp collar shirt featuring bespoke artisanal hand-dyed Adire motifs on premium linen.',
    price: 3500000,
    compareAtPrice: 4200000,
    category: 'Tops',
    materials: '100% Handcrafted Indigo Linen',
    careInstructions: 'Hand wash cold separately. Line dry in shade.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-5-1', url: '/images/antho-shoot/IMG_3804.JPG', alt: 'Adire Camp Shirt Front', position: 0 },
      { id: 'img-5-2', url: '/images/antho-shoot/Snapchat-848713023.jpg', alt: 'Adire Camp Shirt Detail', position: 1 },
    ],
    variants: [
      { id: 'v-5-m', size: 'M', color: 'Indigo', colorHex: '#1E3A8A', stock: 5 },
      { id: 'v-5-l', size: 'L', color: 'Indigo', colorHex: '#1E3A8A', stock: 5 },
    ],
  },
  {
    id: 'prod-6',
    name: 'Oshodi Technical Cargo Pants',
    slug: 'oshodi-cargo',
    description: 'Technical street cargo pants with articulated knee darting, 3D utility cargo compartments, and bungee cinch hems.',
    price: 5000000,
    compareAtPrice: null,
    category: 'Bottoms',
    materials: 'Water-resistant Ripstop Cotton Nylon',
    careInstructions: 'Machine wash delicate. Do not tumble dry.',
    isPublished: true,
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-6-1', url: '/images/antho-shoot/IMG_3805.JPG', alt: 'Oshodi Cargo Pants Front', position: 0 },
      { id: 'img-6-2', url: '/images/antho-shoot/Snapchat-903653531.jpg', alt: 'Oshodi Cargo Pants Details', position: 1 },
    ],
    variants: [
      { id: 'v-6-s', size: 'S', color: 'Olive Green', colorHex: '#3F4836', stock: 10 },
      { id: 'v-6-m', size: 'M', color: 'Olive Green', colorHex: '#3F4836', stock: 12 },
      { id: 'v-6-l', size: 'L', color: 'Olive Green', colorHex: '#3F4836', stock: 7 },
    ],
  },
  {
    id: 'prod-7',
    name: 'Mainland Boxy Denim Jacket',
    slug: 'mainland-denim',
    description: 'Cropped, boxy denim jacket made from 14oz raw Japanese selvedge denim with custom ANTHO silver-tone engraved hardware.',
    price: 7500000,
    compareAtPrice: 8500000,
    category: 'Outerwear',
    materials: '14oz Raw Selvedge Cotton Denim',
    careInstructions: 'Spot clean or dry clean to preserve raw denim stiffness.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-7-1', url: '/images/antho-shoot/IMG_3808.JPG', alt: 'Mainland Denim Jacket Front', position: 0 },
      { id: 'img-7-2', url: '/images/antho-shoot/photo_1_2026-09-04_09-11-37.jpg', alt: 'Mainland Denim Jacket Editorial', position: 1 },
    ],
    variants: [
      { id: 'v-7-m', size: 'M', color: 'Raw Indigo', colorHex: '#1E293B', stock: 8 },
      { id: 'v-7-l', size: 'L', color: 'Raw Indigo', colorHex: '#1E293B', stock: 6 },
    ],
  },
  {
    id: 'prod-8',
    name: 'Ikoyi Open-Knit Polo',
    slug: 'ikoyi-knit-polo',
    description: 'Breathable textured crochet open-knit polo shirt. Features a relaxed collar and delicate ribbed hem.',
    price: 3200000,
    compareAtPrice: null,
    category: 'Tops',
    materials: '100% Breathable Mercerized Cotton Yarn',
    careInstructions: 'Hand wash cold. Dry flat.',
    isPublished: true,
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-8-1', url: '/images/antho-shoot/Snapchat-1079248294.jpg', alt: 'Ikoyi Knit Polo Front', position: 0 },
      { id: 'img-8-2', url: '/images/antho-shoot/Snapchat-1522984318.jpg', alt: 'Ikoyi Knit Polo Detail', position: 1 },
    ],
    variants: [
      { id: 'v-8-s', size: 'S', color: 'Cream', colorHex: '#F5F5DC', stock: 12 },
      { id: 'v-8-m', size: 'M', color: 'Cream', colorHex: '#F5F5DC', stock: 15 },
    ],
  },
];
