import type { Product } from '@/types';

export const sampleProducts: Product[] = [
  // 1. Classic ANTHO Polos
  {
    id: 'prod-polo-1',
    name: 'Classic ANTHO Pique Polo (Onyx Black)',
    slug: 'classic-antho-pique-polo-black',
    description: 'Heavyweight pique cotton polo featuring custom embroidery, relaxed boxy drape, and authentic mother-of-pearl buttons. Inspired by the signature Lagos streetwear polo silhouette.',
    price: 3800000,
    compareAtPrice: 4500000,
    category: 'Classic ANTHO Polos',
    materials: '100% Combed Pique Cotton (280gsm)',
    careInstructions: 'Machine wash cold. Hang dry in shade.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-p1-1', url: '/images/products/polos/photo_1_2026-09-04_09-11-37.jpg', alt: 'Classic ANTHO Pique Polo Front', position: 0 },
      { id: 'img-p1-2', url: '/images/products/polos/Snapchat-1079248294.jpg', alt: 'Classic ANTHO Pique Polo Collar', position: 1 },
      { id: 'img-p1-3', url: '/images/products/polos/Snapchat-848713023.jpg', alt: 'Classic ANTHO Pique Polo Lifestyle', position: 2 },
    ],
    variants: [
      { id: 'v-p1-s', size: 'S', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 12 },
      { id: 'v-p1-m', size: 'M', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 20 },
      { id: 'v-p1-l', size: 'L', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 15 },
      { id: 'v-p1-xl', size: 'XL', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 8 },
    ],
  },
  {
    id: 'prod-polo-2',
    name: 'Classic ANTHO Structured Polo (Vintage Cream)',
    slug: 'classic-antho-structured-polo-cream',
    description: 'Vintage-tinted heavyweight cotton polo shirt with contrast ribbed collar and minimal ANTHO chest insignia.',
    price: 3800000,
    compareAtPrice: null,
    category: 'Classic ANTHO Polos',
    materials: '100% Pique Cotton',
    careInstructions: 'Cold wash. Do not tumble dry.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-p2-1', url: '/images/products/polos/Snapchat-1079248294.jpg', alt: 'Classic ANTHO Structured Polo Front', position: 0 },
      { id: 'img-p2-2', url: '/images/products/polos/Snapchat-848713023.jpg', alt: 'Classic ANTHO Structured Polo Detail', position: 1 },
    ],
    variants: [
      { id: 'v-p2-s', size: 'S', color: 'Vintage Cream', colorHex: '#FFFDD0', stock: 10 },
      { id: 'v-p2-m', size: 'M', color: 'Vintage Cream', colorHex: '#FFFDD0', stock: 16 },
      { id: 'v-p2-l', size: 'L', color: 'Vintage Cream', colorHex: '#FFFDD0', stock: 14 },
    ],
  },
  {
    id: 'prod-polo-3',
    name: 'Classic ANTHO Signature Polo (Stone Gray)',
    slug: 'classic-antho-signature-polo-stone',
    description: 'Washed tone polo cut with dropped shoulders and a structured athletic collar. Everyday essential.',
    price: 4000000,
    compareAtPrice: 4800000,
    category: 'Classic ANTHO Polos',
    materials: '100% Organic Pique Cotton',
    careInstructions: 'Machine wash cold.',
    isPublished: true,
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-p3-1', url: '/images/products/polos/Snapchat-848713023.jpg', alt: 'Classic ANTHO Signature Polo Front', position: 0 },
      { id: 'img-p3-2', url: '/images/products/polos/photo_1_2026-09-04_09-11-37.jpg', alt: 'Classic ANTHO Signature Polo Angle', position: 1 },
    ],
    variants: [
      { id: 'v-p3-m', size: 'M', color: 'Stone Gray', colorHex: '#78716C', stock: 15 },
      { id: 'v-p3-l', size: 'L', color: 'Stone Gray', colorHex: '#78716C', stock: 12 },
    ],
  },

  // 2. ANTHO Sweatpants
  {
    id: 'prod-sweat-1',
    name: 'ANTHO Heavyweight Fleece Sweatpants (Charcoal)',
    slug: 'antho-heavyweight-fleece-sweatpants-charcoal',
    description: '500gsm custom milled fleece sweatpants featuring deep welt pockets, hidden waist drawcords, and a clean baggy fall over sneakers.',
    price: 4800000,
    compareAtPrice: 5800000,
    category: 'ANTHO Sweatpants',
    materials: '100% French Terry Cotton (500gsm)',
    careInstructions: 'Machine wash cold inside out.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-s1-1', url: '/images/products/sweatpants/Snapchat-396574672.jpg', alt: 'ANTHO Heavyweight Sweatpants Front', position: 0 },
      { id: 'img-s1-2', url: '/images/antho-shoot/IMG_3801.JPG', alt: 'ANTHO Sweatpants Lifestyle', position: 1 },
    ],
    variants: [
      { id: 'v-s1-s', size: 'S', color: 'Charcoal', colorHex: '#2A2A2A', stock: 8 },
      { id: 'v-s1-m', size: 'M', color: 'Charcoal', colorHex: '#2A2A2A', stock: 18 },
      { id: 'v-s1-l', size: 'L', color: 'Charcoal', colorHex: '#2A2A2A', stock: 14 },
      { id: 'v-s1-xl', size: 'XL', color: 'Charcoal', colorHex: '#2A2A2A', stock: 6 },
    ],
  },
  {
    id: 'prod-sweat-2',
    name: 'ANTHO Relaxed Cuffed Sweatpants (Washed Black)',
    slug: 'antho-relaxed-cuffed-sweatpants-black',
    description: 'Tapered relaxed sweatpants with elasticated cuffs and subtle tonal script embroidery on the left thigh.',
    price: 4500000,
    compareAtPrice: null,
    category: 'ANTHO Sweatpants',
    materials: '100% Brushed Fleece Cotton',
    careInstructions: 'Machine wash cold.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-s2-1', url: '/images/products/sweatpants/Snapchat-396574672.jpg', alt: 'ANTHO Cuffed Sweatpants Front', position: 0 },
      { id: 'img-s2-2', url: '/images/antho-shoot/IMG_3805.JPG', alt: 'ANTHO Cuffed Sweatpants Fit', position: 1 },
    ],
    variants: [
      { id: 'v-s2-s', size: 'S', color: 'Washed Black', colorHex: '#1C1C1C', stock: 10 },
      { id: 'v-s2-m', size: 'M', color: 'Washed Black', colorHex: '#1C1C1C', stock: 15 },
      { id: 'v-s2-l', size: 'L', color: 'Washed Black', colorHex: '#1C1C1C', stock: 12 },
    ],
  },
  {
    id: 'prod-sweat-3',
    name: 'ANTHO Archival Tailored Trousers (Pitch Black)',
    slug: 'antho-archival-tailored-trousers',
    description: 'Wide-leg tailored form combining streetwear utility with sartorial drape. Double front pleats with inner adjuster tabs.',
    price: 5200000,
    compareAtPrice: 6200000,
    category: 'ANTHO Sweatpants',
    materials: 'Wool Blend Twill',
    careInstructions: 'Dry clean recommended.',
    isPublished: true,
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-s3-1', url: '/images/antho-shoot/IMG_3801.JPG', alt: 'ANTHO Tailored Trousers Front', position: 0 },
      { id: 'img-s3-2', url: '/images/products/sweatpants/Snapchat-396574672.jpg', alt: 'ANTHO Tailored Trousers Close-Up', position: 1 },
    ],
    variants: [
      { id: 'v-s3-m', size: 'M', color: 'Pitch Black', colorHex: '#0A0A0A', stock: 9 },
      { id: 'v-s3-l', size: 'L', color: 'Pitch Black', colorHex: '#0A0A0A', stock: 11 },
    ],
  },

  // 3. ANTHO Graphic Tees
  {
    id: 'prod-tee-1',
    name: 'ANTHO God Is The Greatest Graphic Tee',
    slug: 'antho-god-is-the-greatest-graphic-tee',
    description: 'Signature 300gsm heavyweight boxy tee with archival silk-screen print across chest and back. Pre-shrunk cotton with drop shoulder silhouette.',
    price: 3200000,
    compareAtPrice: 3800000,
    category: 'ANTHO Graphic Tees',
    materials: '100% Heavyweight Cotton (300gsm)',
    careInstructions: 'Wash cold inside out. Do not iron print.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-t1-1', url: '/images/products/tees/Snapchat-1522984318.jpg', alt: 'God Is The Greatest Tee Front', position: 0 },
      { id: 'img-t1-2', url: '/images/products/tees/Snapchat-1782284509.jpg', alt: 'God Is The Greatest Tee Detail', position: 1 },
      { id: 'img-t1-3', url: '/images/products/tees/Snapchat-903653531.jpg', alt: 'God Is The Greatest Tee Fit', position: 2 },
    ],
    variants: [
      { id: 'v-t1-s', size: 'S', color: 'Vintage Black', colorHex: '#141414', stock: 15 },
      { id: 'v-t1-m', size: 'M', color: 'Vintage Black', colorHex: '#141414', stock: 25 },
      { id: 'v-t1-l', size: 'L', color: 'Vintage Black', colorHex: '#141414', stock: 20 },
      { id: 'v-t1-xl', size: 'XL', color: 'Vintage Black', colorHex: '#141414', stock: 10 },
    ],
  },
  {
    id: 'prod-tee-2',
    name: 'ANTHO Lagos Archival Graphic Tee',
    slug: 'antho-lagos-archival-graphic-tee',
    description: 'Custom pigment dyed tee honoring the creative resilience of Lagos. Ribbed collar with reinforced seam taping.',
    price: 3200000,
    compareAtPrice: null,
    category: 'ANTHO Graphic Tees',
    materials: '100% Ring-Spun Cotton',
    careInstructions: 'Machine wash cold.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-t2-1', url: '/images/products/tees/Snapchat-617620438.jpg', alt: 'ANTHO Lagos Archival Tee Front', position: 0 },
      { id: 'img-t2-2', url: '/images/products/tees/Snapchat-903653531.jpg', alt: 'ANTHO Lagos Archival Tee Back', position: 1 },
    ],
    variants: [
      { id: 'v-t2-s', size: 'S', color: 'Charcoal Wash', colorHex: '#262626', stock: 12 },
      { id: 'v-t2-m', size: 'M', color: 'Charcoal Wash', colorHex: '#262626', stock: 18 },
      { id: 'v-t2-l', size: 'L', color: 'Charcoal Wash', colorHex: '#262626', stock: 16 },
    ],
  },
  {
    id: 'prod-tee-3',
    name: 'ANTHO Calligraphy Boxy Tee (Optic White)',
    slug: 'antho-calligraphy-boxy-tee-white',
    description: 'Crisp optic white tee featuring the signature ANTHO calligraphy wordmark and cross logo screen printed in high-density ink.',
    price: 3000000,
    compareAtPrice: 3600000,
    category: 'ANTHO Graphic Tees',
    materials: '100% Combed Cotton',
    careInstructions: 'Machine wash cold with like colors.',
    isPublished: true,
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-t3-1', url: '/images/products/tees/Snapchat-903653531.jpg', alt: 'ANTHO Calligraphy Tee White Front', position: 0 },
      { id: 'img-t3-2', url: '/images/products/tees/Snapchat-1522984318.jpg', alt: 'ANTHO Calligraphy Tee White Model', position: 1 },
    ],
    variants: [
      { id: 'v-t3-s', size: 'S', color: 'Optic White', colorHex: '#FAFAF9', stock: 14 },
      { id: 'v-t3-m', size: 'M', color: 'Optic White', colorHex: '#FAFAF9', stock: 22 },
      { id: 'v-t3-l', size: 'L', color: 'Optic White', colorHex: '#FAFAF9', stock: 18 },
    ],
  },
  {
    id: 'prod-tee-4',
    name: 'ANTHO Heritage Stamp Tee (Raw Black)',
    slug: 'antho-heritage-stamp-tee-black',
    description: 'Raw black heavyweight tee featuring subtle tonal heritage stamp on chest and red cross emblem on collar nape.',
    price: 3000000,
    compareAtPrice: null,
    category: 'ANTHO Graphic Tees',
    materials: '100% Heavyweight Cotton',
    careInstructions: 'Machine wash cold.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-t4-1', url: '/images/products/tees/Snapchat-1782284509.jpg', alt: 'ANTHO Heritage Stamp Tee Front', position: 0 },
      { id: 'img-t4-2', url: '/images/products/tees/Snapchat-617620438.jpg', alt: 'ANTHO Heritage Stamp Tee Back', position: 1 },
    ],
    variants: [
      { id: 'v-t4-m', size: 'M', color: 'Raw Black', colorHex: '#0A0A0A', stock: 16 },
      { id: 'v-t4-l', size: 'L', color: 'Raw Black', colorHex: '#0A0A0A', stock: 20 },
      { id: 'v-t4-xl', size: 'XL', color: 'Raw Black', colorHex: '#0A0A0A', stock: 12 },
    ],
  },
];
