import type { Product } from '@/types';

export const sampleProducts: Product[] = [
  // 1. Classic ANTHO Polo (1 item)
  {
    id: 'antho-99-polo',
    name: "ANTHO 99' POLO",
    slug: 'antho-99-polo',
    description: "Architectural boxy pique polo featuring signature custom embroidery, relaxed drape, and authentic mother-of-pearl buttons. Crafted for the contemporary Lagos youth streetwear aesthetic.",
    price: 4500000,
    category: 'Classic ANTHO Polos',
    materials: '100% Combed Pique Cotton (280gsm)',
    careInstructions: 'Machine wash cold. Hang dry in shade.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-polo-1', url: '/images/products/polos/photo_1_2026-09-04_09-11-37.jpg', alt: "ANTHO 99' POLO Front View", position: 0 },
      { id: 'img-polo-2', url: '/images/products/polos/Snapchat-1079248294.jpg', alt: "ANTHO 99' POLO Collar & Embroidery Detail", position: 1 },
      { id: 'img-polo-3', url: '/images/products/polos/Snapchat-848713023.jpg', alt: "ANTHO 99' POLO Editorial Lifestyle", position: 2 },
    ],
    variants: [
      { id: 'v-polo-s', size: 'S', color: 'White', colorHex: '#FAFAF9', stock: 12 },
      { id: 'v-polo-m', size: 'M', color: 'White', colorHex: '#FAFAF9', stock: 20 },
      { id: 'v-polo-l', size: 'L', color: 'White', colorHex: '#FAFAF9', stock: 15 },
      { id: 'v-polo-xl', size: 'XL', color: 'White', colorHex: '#FAFAF9', stock: 8 },
    ],
  },

  // 2. ANTHO Sweatpants (1 item)
  {
    id: 'antho-npng-sweats',
    name: 'ANTHO “NPNG” SWEATS',
    slug: 'antho-npng-sweats',
    description: '500gsm custom milled heavyweight fleece sweatpants featuring deep welt pockets, hidden waist drawcords, and an intentional stacked fall over sneakers. Streetwear fit engineered for youth and young adults.',
    price: 2500000,
    category: 'ANTHO Sweatpants',
    materials: '100% French Terry Cotton (500gsm)',
    careInstructions: 'Machine wash cold inside out. Do not tumble dry.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-sweat-1', url: '/images/products/sweatpants/Snapchat-396574672.jpg', alt: 'ANTHO “NPNG” SWEATS Front Cut', position: 0 },
      { id: 'img-sweat-2', url: '/images/antho-shoot/IMG_3801.JPG', alt: 'ANTHO “NPNG” SWEATS Stacked Fit', position: 1 },
      { id: 'img-sweat-3', url: '/images/antho-shoot/IMG_3805.JPG', alt: 'ANTHO “NPNG” SWEATS Editorial Lifestyle', position: 2 },
    ],
    variants: [
      { id: 'v-sweat-s', size: 'S', color: 'Charcoal Black', colorHex: '#18181B', stock: 10 },
      { id: 'v-sweat-m', size: 'M', color: 'Charcoal Black', colorHex: '#18181B', stock: 18 },
      { id: 'v-sweat-l', size: 'L', color: 'Charcoal Black', colorHex: '#18181B', stock: 14 },
      { id: 'v-sweat-xl', size: 'XL', color: 'Charcoal Black', colorHex: '#18181B', stock: 8 },
    ],
  },

  // 3. ANTHO Graphic Tee 1 (Tee 1 of 2)
  {
    id: 'antho-global-tee',
    name: 'ANTHO GLOBAL TEE',
    slug: 'antho-global-tee',
    description: '300gsm heavyweight boxy tee with iconic ANTHO Syllogi global insignia print. Custom dropped shoulders, reinforced ribbed neckline, and relaxed drape tailored for contemporary streetwear styling.',
    price: 3000000,
    category: 'ANTHO Graphic Tees',
    materials: '100% Heavyweight Combed Cotton (300gsm)',
    careInstructions: 'Wash cold inside out. Do not iron print directly.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-global-1', url: '/images/gridimg/global_tee.png', alt: 'ANTHO GLOBAL TEE Isolated Product View', position: 0 },
      { id: 'img-global-2', url: '/images/global_white/IMG_6580.JPEG', alt: 'ANTHO GLOBAL TEE White Studio Front', position: 1 },
      { id: 'img-global-3', url: '/images/global_white/IMG_6733.JPEG', alt: 'ANTHO GLOBAL TEE White Graphic Detail', position: 2 },
      { id: 'img-global-4', url: '/images/global_white/IMG_6710.JPEG', alt: 'ANTHO GLOBAL TEE Editorial Look', position: 3 },
      { id: 'img-global-5', url: '/images/global_black/global_black_BACK.png', alt: 'ANTHO GLOBAL TEE Onyx Black Back Print', position: 4 },
      { id: 'img-global-6', url: '/images/global_black/front_glbl.png', alt: 'ANTHO GLOBAL TEE Onyx Black Front Silhouette', position: 5 },
      { id: 'img-global-7', url: '/images/global_black/IMG_6729.JPEG', alt: 'ANTHO GLOBAL TEE Onyx Black Close Up', position: 6 },
    ],
    variants: [
      { id: 'v-global-w-s', size: 'S', color: 'White', colorHex: '#FAFAF9', stock: 15 },
      { id: 'v-global-w-m', size: 'M', color: 'White', colorHex: '#FAFAF9', stock: 25 },
      { id: 'v-global-w-l', size: 'L', color: 'White', colorHex: '#FAFAF9', stock: 20 },
      { id: 'v-global-w-xl', size: 'XL', color: 'White', colorHex: '#FAFAF9', stock: 10 },
      { id: 'v-global-b-s', size: 'S', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 15 },
      { id: 'v-global-b-m', size: 'M', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 25 },
      { id: 'v-global-b-l', size: 'L', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 20 },
      { id: 'v-global-b-xl', size: 'XL', color: 'Onyx Black', colorHex: '#0A0A0A', stock: 10 },
    ],
  },

  // 4. ANTHO Graphic Tee 2 (Tee 2 of 2)
  {
    id: 'antho-prevails-tee',
    name: 'ANTHO PREVAILS TEE',
    slug: 'antho-prevails-tee',
    description: 'Signature 300gsm heavyweight cotton tee featuring the iconic ANTHO PREVAILS artwork. High-density silkscreen print designed to endure heavy wear while retaining rich texture.',
    price: 1500000,
    category: 'ANTHO Graphic Tees',
    materials: '100% Heavyweight Cotton (300gsm)',
    careInstructions: 'Machine wash cold inside out. Hang dry.',
    isPublished: true,
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      { id: 'img-prevails-1', url: '/images/gridimg/white_prevails.png', alt: 'ANTHO PREVAILS TEE White Product View', position: 0 },
      { id: 'img-prevails-2', url: '/images/gridimg/black_prevails.png', alt: 'ANTHO PREVAILS TEE Black Product View', position: 1 },
      { id: 'img-prevails-3', url: '/images/white_prevails/IMG_6714.JPEG', alt: 'ANTHO PREVAILS TEE White Editorial Model', position: 2 },
      { id: 'img-prevails-4', url: '/images/white_prevails/IMG_6590.JPEG', alt: 'ANTHO PREVAILS TEE White Back Graphic', position: 3 },
      { id: 'img-prevails-5', url: '/images/black_prevails/IMG_4911.jpg', alt: 'ANTHO PREVAILS TEE Black Street Style', position: 4 },
      { id: 'img-prevails-6', url: '/images/black_prevails/IMG_6738.JPEG', alt: 'ANTHO PREVAILS TEE Black Detail', position: 5 },
    ],
    variants: [
      { id: 'v-prevails-w-s', size: 'S', color: 'White', colorHex: '#FAFAF9', stock: 15 },
      { id: 'v-prevails-w-m', size: 'M', color: 'White', colorHex: '#FAFAF9', stock: 25 },
      { id: 'v-prevails-w-l', size: 'L', color: 'White', colorHex: '#FAFAF9', stock: 20 },
      { id: 'v-prevails-w-xl', size: 'XL', color: 'White', colorHex: '#FAFAF9', stock: 10 },
      { id: 'v-prevails-b-s', size: 'S', color: 'Black', colorHex: '#0A0A0A', stock: 15 },
      { id: 'v-prevails-b-m', size: 'M', color: 'Black', colorHex: '#0A0A0A', stock: 25 },
      { id: 'v-prevails-b-l', size: 'L', color: 'Black', colorHex: '#0A0A0A', stock: 20 },
      { id: 'v-prevails-b-xl', size: 'XL', color: 'Black', colorHex: '#0A0A0A', stock: 10 },
    ],
  },
];
